[package]
name = "move_window"
version = "0.3.0"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
edition = "2018"

[dependencies]
objc = "0.2.5"
core-foundation = "0.6.4"
cocoa = "0.19.0"
serde_derive = "1.0.89"
osascript = "0.3.0"
serde = "1.0.89"
